all:
  children:
    pbs_servers:
      hosts:
        pbs1:
          ansible_host: 10.0.0.179
    lxc_containers:
      hosts:
        caddy:
          ansible_host: 10.0.0.185
        docmost:
          ansible_host: 10.0.0.177
        paperless:
          ansible_host: 10.0.0.181
        postiz:
          ansible_host: 10.0.0.186