- name: Backup Paperless-NGX and copy to OMV SMB share
  hosts: paperless
  become: true
  remote_user: ansible_user
  vars:
    backup_dir: /tmp/paperless_backups
    backup_file: "{{ backup_dir }}/paperless-backup-{{ ansible_date_time.date }}"
    smb_mount: /mnt/omv_backup
    smb_share: "//10.0.0.178/omv_data"
  # smb_user and smb_pass are now loaded from vault
  # backup_zip_pass is also loaded from vault

  tasks:
    - name: Load vault variables
      include_vars: ../inventories/group_vars/paperless/paperless_vault.yml

    # Ensure required packages are installed
    - name: Ensure cifs-utils is installed (Debian/Ubuntu)
      apt:
        name: cifs-utils
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Ensure cifs-utils is installed (RedHat/CentOS/Fedora)
      dnf:
        name: cifs-utils
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Ensure gpg is installed (Debian/Ubuntu)
      apt:
        name: gnupg
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Ensure gpg is installed (RedHat/CentOS/Fedora)
      dnf:
        name: gnupg2
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Ensure smbclient is installed (Debian/Ubuntu)
      apt:
        name: smbclient
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Ensure smbclient is installed (RedHat/CentOS/Fedora)
      dnf:
        name: smbclient
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Run Paperless-NGX backup
      command: >
        python3 manage.py document_exporter {{ backup_dir }} -z --no-progress-bar -zn {{ backup_file }}
      args:
        chdir: /opt/paperless/src
        creates: "{{ backup_file }}"

    - name: Encrypt the Paperless-NGX backup zip file with GPG and password
      command: >
        gpg --batch --yes --passphrase "{{ backup_zip_pass }}" -c "{{ backup_file }}.zip"
      args:
        chdir: "{{ backup_dir }}"

    - name: Copy backup to SMB share using smbclient
      command: >
        smbclient "{{ smb_share }}" -U "{{ smb_user }}%{{ smb_pass }}" -c "mkdir paperless-backup; put {{ backup_file }}.zip.gpg paperless-backup/{{ backup_file | basename }}.zip.gpg"
      args:
        chdir: "{{ backup_dir }}"
      register: smbclient_result
      #no_log: true

    # Get checksum of the local and remote encrypted backup file
    - name: Calculate checksum of remote backup file
      stat:
        path: "paperless-backup/{{ backup_file | basename }}.zip.gpg"
        checksum_algorithm: sha256
      register: remote_backup_stat

    - name: Calculate checksum of archive
      stat:
        path: "{{ backup_file }}.zip.gpg"
        checksum_algorithm: sha256
      register: local_backup_stat
      delegate_to: localhost

    - name: Assert checksums match
      assert:
        that:
          - local_backup_stat.stat.checksum == remote_backup_stat.checksum
        fail_msg: "Checksum mismatch for the backup file. Local: {{ local_backup_stat.stat.checksum }}, Remote: {{ remote_backup_stat.stat.checksum }}"

    - name: Remove all files in backup_dir if backup was successful
      file:
        path: "{{ backup_dir }}"
        state: absent
      when: smbclient_result is succeeded